--
-- BSD 3-Clause License
--
-- Copyright (c) 2024, TuneURL Inc.
--
-- Redistribution and use in source and binary forms, with or without
-- modification, are permitted provided that the following conditions are met:
--
-- 1. Redistributions of source code must retain the above copyright notice, this
--    list of conditions and the following disclaimer.
--
-- 2. Redistributions in binary form must reproduce the above copyright notice,
--    this list of conditions and the following disclaimer in the documentation
--    and/or other materials provided with the distribution.
--
-- 3. Neither the name of the copyright holder nor the names of its
--    contributors may be used to endorse or promote products derived from
--    this software without specific prior written permission.
--
-- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
-- AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
-- IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
-- DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
-- FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
-- DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
-- SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
-- CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
-- OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
-- OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
--
-- mysqladmin --user=root --password=$PASSWORD drop poctuneurl
-- mysql --user=root --password=$PASSWORD < db/init.sql
-- mysqlshow --user=root --password=$PASSWORD
-- +--------------------+
-- |     Databases      |
-- +--------------------+
-- | information_schema |
-- | mysql              |
-- | performance_schema |
-- | sys                |
-- | poctuneurl         |
-- +--------------------+
--
-- MySQL Script generated by MySQL Workbench
-- Saturday, 29 July, 2023 01:50:07 AM
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema poctuneurl
-- -----------------------------------------------------
-- CREATE SCHEMA IF NOT EXISTS `poctuneurl` ;

-- -----------------------------------------------------
-- Schema poctuneurl
-- -----------------------------------------------------
USE `poctuneurl` ;

-- -----------------------------------------------------
-- Table `poctuneurl`.`sdk_user` SdkUser
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poctuneurl`.`sdk_user` ;

CREATE TABLE IF NOT EXISTS `poctuneurl`.`sdk_user` (
  `su_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'User ID',
  `su_email` VARCHAR(254) NOT NULL COMMENT 'User Email',
  `su_fullname` VARCHAR(254) NOT NULL COMMENT 'User Fullname',
  `su_roles` VARCHAR(48) NOT NULL COMMENT 'User Roles',
  `su_ldap` BIGINT NOT NULL COMMENT 'User LDAP ID',
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date Created',
  `su_alias` VARCHAR(16) NULL COMMENT 'User Alias ID',
  PRIMARY KEY (`su_id`)
)
ENGINE = InnoDB
AUTO_INCREMENT=17001001
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'SDK User table';

LOCK TABLES `sdk_user` WRITE;
/*!40000 ALTER TABLE `sdk_user` DISABLE KEYS */;
INSERT INTO `sdk_user` VALUES (17001001,'admin@example.com','admin','ADMIN_ROLE',17001001,'2024-03-13 17:47:07','17001001'),(17001002,'user@example.com','user','USER_ROLE',17001002,'2024-03-04 17:14:56','17001002');
/*!40000 ALTER TABLE `sdk_user` ENABLE KEYS */;
UNLOCK TABLES;

-- -----------------------------------------------------
-- Table `poctuneurl`.`ldap_info` LdapInfo
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poctuneurl`.`ldap_info` ;

CREATE TABLE IF NOT EXISTS `poctuneurl`.`ldap_info` (
  `li_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'LDAP ID',
  `li_pwd` VARCHAR(63) NOT NULL COMMENT 'LDAP password',
  `li_uuid` VARCHAR(36) NOT NULL COMMENT 'LDAP UUID',
  `li_status` BIGINT NOT NULL DEFAULT 0 COMMENT 'LDAP status 0=New, 1=Active, 2=Suspended, 3=Deleted',
  PRIMARY KEY (`li_id`)
)
ENGINE = InnoDB
AUTO_INCREMENT=17001001
COMMENT = 'Simulated LDAP User Data';

LOCK TABLES `ldap_info` WRITE;
/*!40000 ALTER TABLE `ldap_info` DISABLE KEYS */;
INSERT INTO `ldap_info` VALUES (17001001,'hExYWRtaW5AMTIzNCFwYXNzd29yZA==','6c1620a8-c5db-4ad1-a3cc-0bae9164a0d3',1),(17001002,'hExcGFzc3dvcmRAdXNlciExMjM0','a8b03cb0-b293-44b8-b4ec-3e9869c0bcdb',1);
/*!40000 ALTER TABLE `ldap_info` ENABLE KEYS */;
UNLOCK TABLES;

-- -----------------------------------------------------
-- Table `poctuneurl`.`session_data` SessionData
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poctuneurl`.`session_data` ;

CREATE TABLE IF NOT EXISTS `poctuneurl`.`session_data` (
  `sd_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Session ID',
  `sd_ldap_id` BIGINT NOT NULL COMMENT 'Session LDAP ID',
  `sd_ip_addr` VARCHAR(45) NOT NULL COMMENT 'IP Address',
  `sd_start` DATETIME NOT NULL COMMENT 'Start Session datetime',
  `sd_end` DATETIME NOT NULL COMMENT 'End Session datetime',
  PRIMARY KEY (`sd_id`)
)
ENGINE = InnoDB
AUTO_INCREMENT=18002001
COMMENT = 'Session Data for API call rate limiting';

LOCK TABLES `session_data` WRITE;
/*!40000 ALTER TABLE `session_data` DISABLE KEYS */;
INSERT INTO `session_data` VALUES (18002001,17001001,'172.31.30.201','2024-03-13 17:47:07','2024-03-13 17:47:07'),(18002002,17001002,'172.31.30.201','2024-03-02 07:43:13','2024-03-02 07:43:13');
/*!40000 ALTER TABLE `session_data` ENABLE KEYS */;
UNLOCK TABLES;

-- -----------------------------------------------------
-- Table `poctuneurl`.`audio_stream_data` AudioStreamData
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poctuneurl`.`audio_stream_data` ;

CREATE TABLE IF NOT EXISTS `poctuneurl`.`audio_stream_data` (
  `as_id` bigint NOT NULL AUTO_INCREMENT,
  `as_duration` bigint NOT NULL DEFAULT '0',
  `as_filename` VARCHAR(48) NOT NULL,
  `as_status` INT UNSIGNED NOT NULL DEFAULT '0',
  `as_url` VARCHAR(4096) NOT NULL,
  `as_created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `as_modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`as_id`))
ENGINE = InnoDB
AUTO_INCREMENT=19003001
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Audio Stream Data';

CREATE UNIQUE INDEX `uq_audio_stream_data_as_id` ON `poctuneurl`.`audio_stream_data` (`as_id` ASC) VISIBLE;

LOCK TABLES `audio_stream_data` WRITE;
/*!40000 ALTER TABLE `audio_stream_data` DISABLE KEYS */;
/*!40000 ALTER TABLE `audio_stream_data` ENABLE KEYS */;
UNLOCK TABLES;

-- -----------------------------------------------------
-- Table `poctuneurl`.`fingerprints` FingerPrintsData
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poctuneurl`.`fingerprints` ;

CREATE TABLE IF NOT EXISTS `poctuneurl`.`fingerprints` (
  `fp_id` bigint NOT NULL AUTO_INCREMENT,
  `fp_as_id` bigint NOT NULL,
  `fp_offset` INT UNSIGNED NOT NULL,
  `fp_created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fp_modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `fk_fingerprints_fp_as_id`
    FOREIGN KEY (`fp_as_id`)
    REFERENCES `poctuneurl`.`audio_stream_data` (`as_id`)
    ON DELETE CASCADE,
  PRIMARY KEY (`fp_id`))
ENGINE = InnoDB
AUTO_INCREMENT=20004001
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Audio Stream Fingerprint';

CREATE UNIQUE INDEX `uq_fingerprints_fp_as_id_fp_offset` ON `poctuneurl`.`fingerprints` (`fp_as_id` ASC, `fp_offset` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `poctuneurl`.`audio_stream_data` AudioStreamTrainingChannel
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poctuneurl`.`audio_stream_channel` ;

CREATE TABLE IF NOT EXISTS `poctuneurl`.`audio_stream_channel` (
  `ac_id` bigint NOT NULL AUTO_INCREMENT,
  `ac_channel` bigint NOT NULL,
  `ac_offset` bigint NOT NULL DEFAULT '0',
  `ac_duration` bigint NOT NULL DEFAULT '0',
  `ac_category` VARCHAR(64) NOT NULL,
  `ac_title` VARCHAR(512) NOT NULL,
  `ac_url` VARCHAR(4096) NOT NULL,
  `ac_filename` VARCHAR(384) NOT NULL,
  `ac_popup` MEDIUMTEXT NOT NULL,
  `ac_status` INT UNSIGNED NOT NULL DEFAULT '0',
  `ac_created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ac_modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ac_id`))
ENGINE = InnoDB
AUTO_INCREMENT=30005013
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Audio Stream Channel';

LOCK TABLES `audio_stream_channel` WRITE;
/*!40000 ALTER TABLE `audio_stream_channel` DISABLE KEYS */;
INSERT INTO `audio_stream_channel` VALUES (30005001,1,2365,5063,'save_page','Prince Pasta Anthony! Commercial Turns 50, Continues To Resonate','https://radio.tmalbon.com/audio/v3/ExampleTurl_Save_NPR_Story.mp3','ExampleTurl_Save_NPR_Story.mp3','hExPHRhYmxlPjx0Ym9keT48dHI+CiAgPHRkPjxzcGFuIGNsYXNzPSJpbnN0cnVjdGlvbnNwYW4iPkxpbms6PC9zcGFuPjwvdGQ+PHRkPjxhIGhyZWY9Imh0dHBzOi8vd3d3Lm5wci5vcmcvMjAxOS8xMS8xOS83ODA5NDkyMDgvcHJpbmNlLXBhc3RhLWFudGhvbnktY29tbWVyY2lhbC10dXJucy01MC1jb250aW51ZXMtdG8tcmVzb25hdGUiIHRhcmdldD0iX2JsYW5rIj5wcmluY2UtcGFzdGEtYW50aG9ueS1jb21tZXJjaWFsLXR1cm5zLTUwLWNvbnRpbnVlcy10by1yZXNvbmF0ZTwvYT48L3RkPgo8L3RyPgo8dHI+CiAgPHRkPjxzcGFuIGNsYXNzPSJpbnN0cnVjdGlvbnNwYW4iPlRpdGxlOjwvc3Bhbj48L3RkPjx0ZD5QcmluY2UgUGFzdGEgJ0FudGhvbnkhJyBDb21tZXJjaWFsIFR1cm5zIDUwLCBDb250aW51ZXMgVG8gUmVzb25hdGU8L3RkPgo8L3RyPgo8dHI+CiAgPHRkPjxzcGFuIGNsYXNzPSJpbnN0cnVjdGlvbnNwYW4iPkRhdGU6PC9zcGFuPjwvdGQ+PHRkPk5PVkVNQkVSIDE5LCAyMDE5IDQ6MjQgUE0gRVQ8L3RkPgo8L3RyPgo8dHI+CiAgPHRkPjxzcGFuIGNsYXNzPSJpbnN0cnVjdGlvbnNwYW4iPkZyb206PC9zcGFuPjwvdGQ+PHRkPkhFQVJEIE9OIEFMTCBUSElOR1MgQ09OU0lERVJFRCBGUk9NIDxhIGhyZWY9Imh0dHBzOi8vd3d3LndidXIub3JnLyIgdGFyZ2V0PSJfYmxhbmsiPldCVVI8L2E+PC90ZD4KPC90cj4KPHRyPgogIDx0ZD48c3BhbiBjbGFzcz0iaW5zdHJ1Y3Rpb25zcGFuIj5CeTo8L3NwYW4+PC90ZD48dGQ+SmFtZXMgQm9sb2duYTwvdGQ+CjwvdHI+Cjx0cj4KICA8dGQ+PHNwYW4gY2xhc3M9Imluc3RydWN0aW9uc3BhbiI+U3Rvcnk6PC9zcGFuPjwvdGQ+PHRkPjx0ZXh0YXJlYSBjbGFzcz0ic3RvcmllcyIgcmVhZG9ubHk9IiI+SW4gMTk2OSwgUHJpbmNlIFBhc3RhIGRlYnV0ZWQgYSBUViBjb21tZXJjaWFsIHNldCBpbiBCb3N0b24ncyBMaXR0bGUgSXRhbHkuIEZpZnR5IHllYXJzIGxhdGVyLCB0aGUgYWQgaXMgaWNvbmljIGluIEJvc3RvbiwgYW5kIGhlbHBlZCBsYXVuY2ggSXRhbGlhbiBBbWVyaWNhbnMgYW5kIHRoZWlyIGZvb2QgaW50byBBbWVyaWNhJ3MgaG9tZXMuPC90ZXh0YXJlYT48L3RkPgo8L3RyPgo8L3Rib2R5PjwvdGFibGU+Cg==',0,'2024-03-13 17:47:07','2024-04-11 10:06:35'),(30005002,2,0,10,'category','title','url','filename','popup',0,'2024-03-13 17:47:07','2024-03-13 17:47:07'),(30005003,3,0,10,'category','title','url','filename','popup',0,'2024-03-13 17:47:07','2024-03-13 17:47:07'),(30005004,4,0,10,'category','title','url','filename','popup',0,'2024-03-13 17:47:07','2024-03-13 17:47:07'),(30005005,5,97178,94000,'save_page','Mae Muller--Better Days (feat. Polo G)--EP','https://radio.tmalbon.com/audio/audio-streams.mp3','audio-streams.mp3','hExPHRhYmxlPjx0Ym9keT48dHI+CiAgPHRkPjxzcGFuIGNsYXNzPSJpbnN0cnVjdGlvbnNwYW4iPkxpbms6PC9zcGFuPjwvdGQ+PHRkPjxhIGhyZWY9Imh0dHBzOi8vbXVzaWMuYXBwbGUuY29tL3VzL3NvbmcvYmV0dGVyLWRheXMtZmVhdC1wb2xvLWcvMTYwNTc2MDQ3NCIgdGFyZ2V0PSJfYmxhbmsiPmJldHRlci1kYXlzLWZlYXQtcG9sby1nLTE2MDU3NjA0NzQ8L2E+PC90ZD4KPC90cj4KPHRyPgogIDx0ZD48c3BhbiBjbGFzcz0iaW5zdHJ1Y3Rpb25zcGFuIj5UaXRsZTo8L3NwYW4+PC90ZD48dGQ+QmV0dGVyIERheXMgKGZlYXQuIFBvbG8gRykgLSBFUDwvdGQ+CjwvdHI+Cjx0cj4KICA8dGQ+PHNwYW4gY2xhc3M9Imluc3RydWN0aW9uc3BhbiI+RGF0ZTo8L3NwYW4+PC90ZD48dGQ+SmFudWFyeSAxOSwgMjAyMjwvdGQ+CjwvdHI+Cjx0cj4KICA8dGQ+PHNwYW4gY2xhc3M9Imluc3RydWN0aW9uc3BhbiI+RnJvbTo8L3NwYW4+PC90ZD48dGQ+QSBDYXBpdG9sIFJlY29yZHMgVUsgLyBFTUkgcmVsZWFzZSwgKGMpIDIwMjIgTmVpa2VkIENvbGxlY3RpdmUgQUIsIHVuZGVyIGV4Y2x1c2l2ZSBsaWNlbnNlIHRvIFVuaXZlcnNhbCBPcGVyYXRpb25zIExpbWl0ZWQ8L3RkPgo8L3RyPgo8dHI+CiAgPHRkPjxzcGFuIGNsYXNzPSJpbnN0cnVjdGlvbnNwYW4iPkJ5Ojwvc3Bhbj48L3RkPjx0ZD5ORUlLRUQsIE1hZSBNdWxsZXIsIEogQmFsdmluPC90ZD4KPC90cj4KPHRyPgogIDx0ZD48c3BhbiBjbGFzcz0iaW5zdHJ1Y3Rpb25zcGFuIj5TdG9yeTo8L3NwYW4+PC90ZD48dGQ+PHRleHRhcmVhIGNsYXNzPSJzdG9yaWVzIiByZWFkb25seT0iIj5Xb3VsZCB5b3UgbGlrZSB0byBoZWFyIHRoZSBjb25jZXJ0IGZyb20gdGhlIHBlcnNwZWN0aXZlIG9mIHN0YW5kaW5nIG5leHQgdG8gaGVyLCB0aGUgZHJ1bW1lciBvZiB0aGUgYmFja2dyb3VuZCBzaW5nZXJzPyBJIGxvdmUgeW91IGd1eXMgc28gbXVjaCBhbmQgSSBsb3ZlIHlvdSBNYWx0YS4gVGhpcyBpcyBteSBsYXN0IHNvbmcuIFNvIHBsZWFzZSBqdXN0IGhhdmUgYSBnb29kIHRpbWUuIEJlIHdpdGggbWUuIEkgTWFlIGFuZCB0aGlzIGlzIGJldHRlciBhbmQgeW91IGNhbid0IG1ha2UgZnJpZW5kcyBwcmF5IGZvciB0aGF0IDMwMCBLIGEgc2hvcnQgcGF1c2Ugb2YgdGhlIHBlcmZvcm1hbmNlLiBXb3VsZCB5b3UgbGlrZSB0byBoZWFyIHRoZSByZXN0IG9mIHRoZSBjb25jZXJ0PyBOb3cgZnJvbSB0aGUgcGVyc3BlY3RpdmUgb2Ygc3RhbmRpbmcgbmV4dCB0byBtZSBNdWxsZXIsIHRoZSBkcnVtbWVyIG9yIHRoZSBiYWNrZ3JvdW5kIHNpbmdlcnM/IE5vLCBhbmQgSSwgaGV5LCBubywgbm8uIEFsbCBJIGhhdmUgdG8gZG8gaXMgc2l0IGFuZCBJIGZvciwgaGV5LCBPbGEsIHNpdCBhcm91bmQsIEknbGwgd2FpdCBmb3IgYmV0dGVyIG9uZSBtb3JlIHRpbWUgc3RheWluZyBpbiB0aGUgc2hhZGUuIEFsbCBJIGRvIGlzIHNpdHRpbmcgYXJvdW5kIGFuZCBJIGZlZWwgYmV0dGVyLiBJIGNhbid0IGNhbiBJIGdldCBhbiBhaXIgaHVtYW4gQWxvbnpvIGFuZCBzaXQgYXJvdW5kIGFuZCB3YWl0IGZvciBiZXR0ZXIgdG9kYXk/IE9rLiBJZiB5b3UgbG92ZSBNYWUgTWlsbGVyLCBhcyBtdWNoIGFzIHdlIGRvLCB0aGVyZSBpcyBhIHF1aWNrIGxpbmsgdG8gZG93bmxvYWQgYmV0dGVyIGRheXMgZnJvbSBNYWUgTXVsbGVyIGZyb20gaVR1bmVzLiBOb3csIHdlIHdhbnRlZCB0byB0aGFuayBCQkMgUGFyYW1vdW50IEtpbmcncyBDb2xsZWdlLCBJIEJDLCBNYWdpYyBCZWFucyBhbmQgd2hpdGUgbGlnaHQgZm9yIHRoZWlyIHN1cHBvcnQgdG8gc2V0IHRoaXMgdXAuIFdlIHdvdWxkIGFwcHJlY2lhdGUgaXQgaWYgeW91IGNvbXBsZXRlIGEgcXVpY2sgc3VydmV5LjwvdGV4dGFyZWE+PC90ZD4KPC90cj4KPC90Ym9keT48L3RhYmxlPgo8IS0tIEhZUEVSTElOSz0iaHR0cHM6Ly9tdXNpYy5hcHBsZS5jb20vdXMvc29uZy9iZXR0ZXItZGF5cy1mZWF0LXBvbG8tZy8xNjA1NzYwNDc0IiAtLT4K',0,'2024-03-13 17:47:07','2024-04-11 10:58:31'),(30005006,6,2025,1020000,'live','TuneUrl full demo','https://radio.tmalbon.com/audio/10240-audio-streams.wav','10240-audio-streams.wav','hExPHA+PC9wPgo8IS0tIEhZUEVSTElOSz0iaHR0cHM6Ly9tdXNpYy5hcHBsZS5jb20vdXMvc29uZy9iZXR0ZXItZGF5cy1mZWF0LXBvbG8tZy8xNjA1NzYwNDc0IiAtLT4=',1,'2024-03-13 17:47:07','2024-03-13 17:47:07'),(30005007,7,0,10,'category','title','url','filename','popup',0,'2024-03-13 17:47:07','2024-03-13 17:47:07'),(30005008,8,0,10,'category','title','url','filename','popup',0,'2024-03-13 17:47:07','2024-03-13 17:47:07'),(30005009,9,0,10,'category','title','url','filename','popup',0,'2024-03-13 17:47:07','2024-03-13 17:47:07'),(30005010,10,0,10,'category','title','url','filename','popup',0,'2024-03-13 17:47:07','2024-03-13 17:47:07'),(30005011,11,0,10,'category','title','url','filename','popup',0,'2024-03-13 17:47:07','2024-03-13 17:47:07'),(30005012,12,0,10,'category','title','url','filename','popup',0,'2024-03-13 17:47:07','2024-03-13 17:47:07');
/*!40000 ALTER TABLE `audio_stream_channel` ENABLE KEYS */;
UNLOCK TABLES;

COMMIT ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
